# Debug code

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -55,6 +55,8 @@ jobs:
         run: |
           docker run --rm -d --name fail2ban --network host --cap-add NET_ADMIN --cap-add NET_RAW rapydo/${{ matrix.service }}:${RAPYDO_VERSION}
 
+          echo "DEBUG CODE: forced fail";
+          exit 1
           ipt=$(docker exec fail2ban iptables -L)
           echo $ipt
           echo $ipt | grep --color "DOCKER-USER"
