RAPyDo 2.1 (#33)
* Bump RAPyDo version to 2.1

* Added GitGuardian to pre-commit hooks

* Undo forced installation of google-chrome 88 due performance drop with Cypress (fixed with 8.3.0)

* Replaced angular courtesy page by running the build stage on a offline dist only moved online once completed to reduced downtimes

* Added creation of rabbitmq.conf as compatibility fix for rabbit 3.9

* Dropped obsolete build setups

* Add stub of a test controller image

* Bump mongo to 5.0.2

* Bump neo4j to 4.3.3

* Bump postgres to 13.4

* Bump nginx to 1.21.3

* Bump swagger to 3.52.2

* Bump rabbitmq to 3.9.5

* Bump watchdog to 2.1.5

* Bump ts-json-schema-generator to 0.95.0

* Bump angular-cli to 12.2.6

* Alchemy migrations are now executed at user level

* Bug fix: versions shown in adminer banner

* Bug fix: added alchemy db stamp to create alchemy version table if missing

* Bug fix to correctly manage renewed ssl certificates

* Bump node and @types/node to 16.10.0

* Bump Angular to 12.2.8

* Updated codeql workflow

* Create ossar-analysis.yml

* Create semgrep-analysis.yml

* Added stub of fail2ban image

* Postgres conf: increased max_wal_size from default (1GB) to 2GB to prevent floods of checkpoints are occurring too frequently warning

* Added IP address to postgres logs

* Added experimental backend based on Ubuntu 21.10

* Added syslog-ng to controller container

* Enabled API_AUTOSTART flag also in dev mode

* Fixed adminer and swaggerui builds in testing mode

* Added reload scripts for backend, nginx, angular, celery, fail2ban, adminer, swaggerui

* Fail2ban ignoreip is now dynamically set based on the docker network

* Bug fix: postgres banner script put in the right home path

* Removed chown developer /code from backend entrypoint

* Made apt-get update quieter

* Bug fix: celery process was not re-loadable twice

* Dropped support for watchdog in celery

* Dropped limit req for assets zone

* Added CSP_FRAME_SRC variable to extend the frame-src CSP setting

* Added SSL_FORCE_SELF_SIGNED env variable force generation of self signed certificates

* Bump Cypress to 9.0.0

* Bug fix: self signed certificates was wrongly forcing CN to localhost

* Enhanced first certificate creation on nginx

* Dropped compose v1 dependencies in controller build

* Changed rate limit respond code from default 503 (Service Temporarily Unavailable) to 429 (Too Many Requests)

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -2,8 +2,6 @@ name: Build
 
 on:
   push:
-  # schedule:
-  #   - cron: "0 0 * * *"
   workflow_dispatch:
 
 jobs:
@@ -12,13 +10,14 @@ jobs:
     timeout-minutes: 8
 
     env:
-      RAPYDO_VERSION: "2.0"
+      RAPYDO_VERSION: "2.1"
 
     strategy:
       matrix:
         service:
           [
             backend,
+            backend2110,
             angular,
             angular-test,
             proxy,
@@ -30,6 +29,8 @@ jobs:
             adminer,
             swaggerui,
             registry,
+            controller,
+            fail2ban,
           ]
 
     steps:
@@ -41,8 +42,6 @@ jobs:
           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
       - name: Build the Docker image
         run: |
-          pip3 install git+https://github.com/rapydo/do.git@${RAPYDO_VERSION}
-          rapydo install buildx
           docker buildx version
           docker buildx build \
             --tag rapydo/${{ matrix.service }}:${RAPYDO_VERSION} \
@@ -51,3 +50,62 @@ jobs:
             --build-arg RAPYDO_VERSION=${RAPYDO_VERSION} \
             --push \
             ${{ matrix.service }}
+
+      - name: Test Fail2ban
+        if: ${{ matrix.service == 'fail2ban' }}
+        run: |
+          docker run --rm -d --name fail2ban --network host --cap-add NET_ADMIN --cap-add NET_RAW rapydo/${{ matrix.service }}:${RAPYDO_VERSION}
+
+          ipt=$(docker exec fail2ban iptables -L)
+          echo $ipt
+          echo $ipt | grep --color "DOCKER-USER"
+
+          git clone -b ${RAPYDO_VERSION} https://github.com/rapydo/do.git
+
+          docker cp fail2ban/tests/testbed.syslog fail2ban:/tmp/
+          docker cp do/controller/confs/fail2ban fail2ban:/tmp/
+
+          docker exec fail2ban fail2ban-regex /tmp/testbed.syslog /tmp/fail2ban/filters/nginx.conf --print-all-matched > /tmp/nginx.matched
+          docker exec fail2ban fail2ban-regex /tmp/testbed.syslog /tmp/fail2ban/filters/nginx.conf --print-all-missed > /tmp/nginx.missed
+
+          # Verify that all rules have matches on the testbed
+          EXPECTED_RULES=$(grep -E "^\s+\^%\(prefix\)s<HOST>" do/controller/confs/fail2ban/filters/nginx.conf  | wc -l)
+          echo "Expected ${EXPECTED_RULES} rules in nginx.conf"
+
+          for i in $(seq 1 ${EXPECTED_RULES}); do
+            if ! grep -F "  ${i}) [" /tmp/nginx.matched;
+            then
+              echo "No matches found for rule ${i}";
+              exit 1
+            fi
+          done
+
+          A=$(expr $EXPECTED_RULES + 1)
+          B=$(expr $EXPECTED_RULES + 100)
+          for i in $(seq ${A} ${B}); do
+            if grep -F "  ${i}) [" /tmp/nginx.missed;
+            then
+              echo "No matches expected to be found for rule ${i}";
+              exit 1
+            fi
+          done
+
+          cat fail2ban/tests/testbed.blacklist | while read url
+          do
+            echo "grep -F \"${url}\" /tmp/nginx.matched";
+            if ! grep -F "${url}" /tmp/nginx.matched;
+            then
+              echo "Invalid result, this URL was expected to match: ${url}";
+              exit 1
+            fi
+          done
+
+          cat fail2ban/tests/testbed.whitelist | while read url
+          do
+            echo "grep -F \"${url}\" /tmp/nginx.missed";
+            if ! grep -F "${url}" /tmp/nginx.missed;
+            then
+              echo "Invalid result, this URL was expected to be missed: ${url}";
+              exit 1
+            fi
+          done
